version: '3.3'

services:
  flask-app:
    build: 
      context: .
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mysql+pymysql://admin:admin@mysql/flask
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: flask
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
